specVersion: '1'
services:
  - type: web
    name: FRANK
    env: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
